### ISSUE TITLE
LIS3DSH sensor question confirmation

### ISSUE THREAD

**Issue by MingYuanJeng** [STMicroelectronics/lis3dsh-pid#1]
Q1：
The lis3dsh_id_get() function in lis3dsh_reg.c
lis3dsh_read_reg(ctx, LIS3DSH_INFO1, reg, 3);
According to the user manual should be modified as follows?
lis3dsh_read_reg(ctx, LIS3DSH_WHO_AM_I, reg, 3);
Q2：
The LIS3DSH_I2C_ADD_L definition value in the lis3dsh_reg.h file is 0x3D or 0x3B
According to the manual description:
If the SEL pin is connected to the voltage supply, the address is 0011101b(0x1D), otherwise the address is 0011110b(0x1E) if the SEL pin is connected to ground.
Should the defined value of LIS3DSH_I2C_ADD_L be corrected to 0x1D or 0x1E?
Q3：
platform_read() function in lis3dsh_read_data_polling.c
reg |= 0x80; Why do 0x80 bitor operation?
HAL_I2C_Mem_Read(handle, LIS3DSH_I2C_ADD_L, reg, I2C_MEMADD_SIZE_8BIT, bufp, len, 1000);

Please help to solve these confusions, thank you

**Comment by avisconti** [comment]
> Q1：
> The lis3dsh_id_get() function in lis3dsh_reg.c
> lis3dsh_read_reg(ctx, LIS3DSH_INFO1, reg, 3);
> According to the user manual should be modified as follows?
> lis3dsh_read_reg(ctx, LIS3DSH_WHO_AM_I, reg, 3);

No, the driver is reading 3 regs: INFO1 (0xD), INFO2 (0xE) and WHO_AM_I (0xF).
All 3 regs are required and not only WHO_AM_I

> Q2：
> The LIS3DSH_I2C_ADD_L definition value in the lis3dsh_reg.h file is 0x3D or 0x3B
> According to the manual description:
> If the SEL pin is connected to the voltage supply, the address is 0011101b(0x1D), otherwise the address is 0011110b(0x1E) if the SEL pin is connected to ground.
> Should the defined value of LIS3DSH_I2C_ADD_L be corrected to 0x1D or 0x1E?

No, the I2C add can be defined as 7bit or 8bit. We use 8bit.
If you see 0x3D at 8bit is equivalent to 0x1E at 7bit.
And 0x3B at 8bit is equivalent to 0x1D at 7bit.
So, it is correct

> Q3：
> platform_read() function in lis3dsh_read_data_polling.c
> reg |= 0x80; Why do 0x80 bitor operation?
> HAL_I2C_Mem_Read(handle, LIS3DSH_I2C_ADD_L, reg, I2C_MEMADD_SIZE_8BIT, bufp, len, 1000);

Because the '1' at msb position defines a I2C read operation.

**Comment by avisconti** [comment]
if you have other questions related to this topic pls reopen this issue. 
I'm closing it now.
